### ISSUE TITLE
change from "style" to "Style" in _output.py

### ISSUE THREAD

**Issue by triggerdude33** [repobee/repobee-junit4#108]
Hello! INDA assistant from KTH here

I noticed that the "colored" package in python have changed "style" to "Style". So when I run this repobee plugin it fails with the message "'function' object has no attribute 'RESET'" in "repobee_junit4/_output.py". But if I replace "style" with "Style" in all areas of the file the code runs as normal.

So I think changing all instances of "style" to "Style" in "_output.py" would be a good idea

![2023-12-08_10-43](https://github.com/repobee/repobee-junit4/assets/39418276/cd9acfb8-3a47-4982-93d1-90f3f97cae18)

**Comment by slarse** [comment]
Hi @triggerdude33,

Thanks for the bug report. This is both a problem in that the dependency is outdated, and the fact that it just changed version with a new install of the plugin (because the dependency is not pinned to a specific version).

Feel free to submit a PR to update the behavior to match the latest version if you have the time to do so. Otherwise I'll get around to that (and pinning the dependencies) as soon as I have some extra time.

**Comment by triggerdude33** [comment]
I've created a [pull request now for this issue](https://github.com/repobee/repobee-junit4/pull/109)

**Comment by slarse** [comment]
Fixed in #112

**Comment by slarse** [comment]
@triggerdude33 repobee-junit4 v2.0.0 is now released and available with `repobee plugin install`.
